package org.example.enums;

public enum EConversationStep {
    HOMEWORK_CHOICE,
    HOMEWORK_SEND,
    HOMEWORK_COMMENT_AND_MARK_INPUT,
    BOT_MESSAGE_TEXT_INPUT,
    BOT_MESSAGE_BUTTON_ADD_CHOICE,
    BOT_MESSAGE_BUTTON_INPUT,
    SEND_BOT_MESSAGE_CHOICE,
    SEND_BOT_DOCUMENT,
}
